language: ruby

addons:
  postgresql: "9.4"

services:
  - postgresql
  - redis-server

rvm:
  - 2.4.2

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

before_install:
  - psql -c "CREATE USER \"admin\" WITH CREATEDB PASSWORD 'admin';" -U postgres
  - psql -c "create database \"homeland-test\" WITH OWNER=\"admin\";" -U postgres
  - cp config/config.yml.default config/config.yml
  - cp config/database.yml.default config/database.yml
  - cp config/secrets.yml.default config/secrets.yml

before_script:
  - RAILS_ENV=test bundle exec rake db:migrate

script:
  - bundle exec rubocop .
  - RAILS_ENV=test bundle exec rake

